---
  header_byte: 0xff
  header_size: 2

  footer_byte: 0x11
  footer_size: 2

  escape_byte: 0x22
  length_size: 2

  baud_rate: 115200

  max_payload_size: 1024

  chunk_size: 255
  symbols: 1

  starting_string: "Cloverwatch"